Repository Azure/shrike, pull requests merged in 2021-07, with the labels that each got.

#111 Implement "Strict" validation logic in the "shrike.build.prepare"
  .gitignore
  mkdocs.yml
  requirements/requirements-build.txt
  shrike/__init__.py
  shrike/build/commands/prepare.py
  shrike/build/core/configuration.py
  tests/tests_build/commands/test_prepare.py
  tests/tests_build/core/test_configuration.py
Labels: shrike.build

#86 Enable AML Metrics and Item Logging in shrike.compliant_logging
  .azure-pipelines/cg.yml
  .github/workflows/docs.yml
  .github/workflows/python.yml
  requirements/requirements-dev.txt
  requirements/requirements-logging.txt
  requirements/requirements-pipeline.txt
  setup.py
  shrike/__init__.py
  shrike/compliant_logging/__init__.py
  shrike/compliant_logging/data_conversions.py
  shrike/compliant_logging/logging.py
  shrike/compliant_logging/system_info.py
  tests/tests_compliant_logging/data/dummy_image.png
  tests/tests_compliant_logging/test_data_conversion.py
  tests/tests_compliant_logging/test_logging.py
  tests/tests_compliant_logging/test_system_info.py
Labels: enhancement

#129 Bugfix: Ensure component cli installed at the register step
  shrike/__init__.py
  shrike/build/commands/register.py
Labels: bug

#139 Add documentation on the "strict" component validation
  docs/build/build-for-sign-and-register.md
Labels: documentation

#141 Add docs on the AML metrics logging feature in shrike
  docs/compliant_logging/aml-metrics-logging.md
  docs/compliant_logging/metrics-logging.py
  mkdocs.yml
Labels: documentation, shrike.compliant_logging
